REGISTERY_NAME: "192.168.1.104:5000"
PROJECT_NAME: "${env.JOB_NAME}"
EXIST_TOOLS: false
GRADEL: "gradel"
GIT_BRANCH: "develop"
GIT_KEY: "267895444wdw6494"
GIT_URL: "192.168.1.104:3000/python.git"
CHECK_SECURITY: false
GIT_SECRET: true
GIT_SECRET_IMAGE: "192.168.1.104:5000/trufflehog"
GIT_SECRET_OUT_FILE: "trufflehog.json"
GIT_LEAKS: true
GITLEAKS_IMAGE: "192.168.1.104:5000/gitleaks"
GITLEAKS_FORMAT: "json"
GITLEAKS_OUT_FILE: "gitleaks.json"
DEPLOY_STAGE: false
DEPLOY_ENV: "Production"
DEPLOY_COMMAND: "./deploy.sh"
